# Generated by Django 4.2.7 on 2023-11-25 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_path', models.CharField(blank=True, max_length=40, null=True)),
                ('category', models.CharField(choices=[('Milk', 'Milk'), ('Diaper', 'Diaper'), ('Food & Weaning food', 'Food & Weaning food'), ('Bath & Body care', 'Bath & Body care'), ('Baby accessory', 'Baby accessory'), ('Toy', 'Toy'), ('Bedroom', 'Bedroom'), ('Clothes', 'Clothes'), ('Towel', 'Towel'), ('Orther', 'Orther')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.SmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('products', models.ManyToManyField(to='shop.product')),
            ],
        ),
    ]
