# Generated by Django 4.2.7 on 2023-11-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deliver',
            field=models.BooleanField(default=False),
        ),
    ]
